stages:
    get_data:
        cmd: python src/stage01_get_data.py --config=configs/config.yaml
        deps: 
            - src/stage01_get_data.py
            - src/utils/common_utils.py
            - configs/config.yaml
        outs:
            - data/cat
            - data/dog

    prepare_base_model:
        cmd: python src/stage02_prepare_base_model.py --config=configs/config.yaml --params=params.yaml
        deps:
            - src/stage02_prepare_base_model.py
            - src/utils/common_utils.py
            - src/utils/model.py
            - configs/config.yaml
        params:
            - IMAGE_SIZE
            - LEARNING_RATE
        outs:
            - artifacts/base_model/updated_VGG16_model.h5
            - artifacts/base_model/VGG16_base_model.h5

    prepare_callbacks:
        cmd: python src/stage03_prepare_callbacks.py --config=configs/config.yaml 
        deps:
            - src/stage03_prepare_callbacks.py
            - src/utils/common_utils.py
            - src/utils/callback_utils.py
            - configs/config.yaml
        outs:
            - artifacts/callbacks/checkpoint_callback.bin
            - artifacts/callbacks/tensorboard_callback.bin

    train_model:
        cmd: python src/stage04_train.py --config=configs/config.yaml --params=params.yaml
        deps:
            - src/stage04_train.py
            - src/utils/common_utils.py
            - src/utils/model.py
            - src/utils/callback_utils.py
            - src/utils/data_management.py
            - artifacts/callbacks/checkpoint_callback.bin
            - artifacts/callbacks/tensorboard_callback.bin
            - artifacts/base_model/updated_VGG16_model.h5
            - data/cat
            - data/dog

            - configs/config.yaml
        params:
            - IMAGE_SIZE
            - BATCH_SIZE
            - EPOCHS
            - AUGMENTATION
        outs:
            - artifacts/trained_model
            - artifacts/tensorboard_log_dir
            - artifacts/checkpoints
