stages:
    get_data:
        cmd: python src/stage01_get_data.py --config=configs/config.yaml
        deps: 
            - src/stage01_get_data.py
            - src/utils/common_utils.py
            - configs/config.yaml
        outs:
            - data/cat
            - data/dog

    prepare_base_model:
        cmd: python src/stage02_prepare_base_model.py --config=configs/config.yaml --params=params.yaml
        deps:
            - src/stage02_prepare_base_model.py
            - src/utils/common_utils.py
            - src/utils/model.py
            - configs/config.yaml
        params:
            - IMAGE_SIZE
            - LEARNING_RATE
        outs:
            - artifacts/base_model/updated_VGG16_model.h5
            - artifacts/base_model/VGG16_base_model.h5