artifacts:
    ARTIFACTS_DIR: "artifacts"
    TRAINED_MODEL_DIR: "trained_model"
    BASE_MODEL_DIR: "base_model"  
    BASE_MODEL_NAME: "VGG16_base_model.h5"
    UPDATED_BASE_MODEL_NAME: "updated_VGG16_model.h5"
    CHECKPOINT_DIR: "checkpoints"
    BASE_LOG_DIR: "base_model_dir"
    TENSORBOARD_ROOT_LOG_DIR: "tensorboard_log_dir"
    CALLBACKS_DIR: "callbacks"
    DATA_DIR: "data"

source_data_download_path:
     - ../source_data/cat
     - ../source_data/dog

local_data_path:
     - data/cat
     - data/dog